version: '3.8'


services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - env/.env.dev
    depends_on:
      - db
  db:
    image: postgis/postgis
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testuser
      - POSTGRES_DB=db_for_spbauto_map
  redis:
    image: "redis:alpine"
  celery:
    build: ./app
    command: celery worker --app=core --loglevel=info
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - env/.env.dev
    depends_on:
      - web
      - redis
volumes:
  postgres_data: