# Generated by Django 3.0.3 on 2020-03-17 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20200302_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='problemlabel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='№'),
        ),
        migrations.AddField(
            model_name='problemlabel',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.Place', verbose_name='населённый пункт'),
        ),
    ]
