# Generated by Django 3.0.3 on 2020-03-18 10:34

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20200317_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemlabel',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
