# Generated by Django 3.0.3 on 2020-04-29 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_problemlabel_house_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemlabel',
            options={'verbose_name_plural': 'Список дорожных проблем'},
        ),
    ]
