# Generated by Django 3.0.3 on 2020-04-29 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_auto_20200429_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Список статусов решения проблем'},
        ),
    ]
