# Generated by Django 3.0.2 on 2020-02-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('seo_description', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('telephone_number', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Основные настройки сайта',
            },
        ),
    ]
