# Generated by Django 3.0.2 on 2020-02-15 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('icon', models.CharField(max_length=60)),
                ('settings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='sitesettings.SiteSettings')),
            ],
            options={
                'verbose_name_plural': 'Ссылки на социальные сети',
            },
        ),
    ]
