# Generated by Django 3.0.3 on 2020-03-02 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemlabel',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='добавлено пользователем'),
        ),
        migrations.AlterField(
            model_name='problemlabel',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='время добавления'),
        ),
        migrations.AlterField(
            model_name='problemlabel',
            name='description',
            field=models.CharField(max_length=500, verbose_name='описание проблемы'),
        ),
        migrations.AlterField(
            model_name='problemlabel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Номер проблемы'),
        ),
        migrations.AlterField(
            model_name='problemlabel',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.Status', verbose_name='статус проблемы'),
        ),
    ]
